### ISSUE TITLE
网易VIP无法播放VIP歌曲

### ISSUE THREAD

**Issue by mc-doge666** [Gunale0926/KO-ON-Bot#21]
已经在config.json配置n_phone,n_password以及值为true的n_cookie,但是重启之后机器人无法播放VIP歌曲，提示播放错误，请重试

**Comment by Vanillekz** [comment]
你的QQ音乐VIP可以播放吗

**Comment by Vanillekz** [comment]
我的倒可以播放VIP  但是进语音不能自动播放以及没有歌词
